apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-data
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/